### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by FutureWL** [minus2718/Estelle#1]
# 这里可以看的见么？

**Comment by minus2718** [comment]
可以了

**Comment by FutureWL** [comment]
恩，这个issuse呢一般是用来反馈BUG或者对项目的建议的。也是项目的开发者与其他用户交流的平台。那以后我们就在这里交流吧。

**Comment by minus2718** [comment]
嗯嗯，好

**Comment by minus2718** [comment]
那个，，我们慢慢来，，我最开始可能很慢，，，不过我智商还是没问题的，比较喜欢数学和物理..

**Comment by minus2718** [comment]
今天，，比较晚了，，我明天很多课，我先碎觉了，，那个，我还不太清楚这个类似消息提醒的东西在哪儿，你要是有时间教，就在知乎上戳一下，，然后，很开心你能教我，我会努力学习的，谢啦.

**Comment by FutureWL** [comment]
恩，在知乎上你能找到我的答案也是缘分。跟你交流我也很开心。你要是有时间也随时在知乎上找我。

**Comment by minus2718** [comment]
周六周日，你什么时候有空，具体，上午下午晚上？  因为我学习的肯定是最基础的，别耽误了你时间

**Comment by FutureWL** [comment]
周六晚上8点吧

**Comment by minus2718** [comment]
嗯，好，你准备从什么开始教起.....（懵.jpg）

**Comment by minus2718** [comment]
我要先看看什么吗？

**Comment by FutureWL** [comment]
从c学还是从java开始

**Comment by minus2718** [comment]
c吧

**Comment by FutureWL** [comment]
好啊，你有c语言的学习资料吗？http://www.runoob.com/cprogramming/c-environment-setup.html 我们用这个做教程可以吧

**Comment by minus2718** [comment]
好，这个标题好符合我，😂

**Comment by FutureWL** [comment]
😂😂

**Comment by minus2718** [comment]
那我们明天晚上八点，线上教学，哈哈哈哈😂

**Comment by minus2718** [comment]
我电脑装了xcode，，，没用过😂

**Comment by FutureWL** [comment]
好啊，不见不散。xcode 这个好，那就用这它😁😁
